# exceptions.py
class InstantiateCSVError(Exception):
    pass
